package com.liushiyu.developer.core.storage;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liushiyu.developer.core.storage.entry.DBTest;

import com.liushiyu.developer.core.storage.DBTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTestDaoConfig;

    private final DBTestDao dBTestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTestDaoConfig = daoConfigMap.get(DBTestDao.class).clone();
        dBTestDaoConfig.initIdentityScope(type);

        dBTestDao = new DBTestDao(dBTestDaoConfig, this);

        registerDao(DBTest.class, dBTestDao);
    }
    
    public void clear() {
        dBTestDaoConfig.clearIdentityScope();
    }

    public DBTestDao getDBTestDao() {
        return dBTestDao;
    }

}
