package com.liushiyu.developer.core.storage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.liushiyu.developer.core.storage.entry.DBTest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "com_liushiyu_developer_db_test".
*/
public class DBTestDao extends AbstractDao<DBTest, Long> {

    public static final String TABLENAME = "com_liushiyu_developer_db_test";

    /**
     * Properties of entity DBTest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property LogTag = new Property(2, String.class, "logTag", false, "LOG_TAG");
        public final static Property LogString = new Property(3, String.class, "logString", false, "LOG_STRING");
    }

    private DaoSession daoSession;


    public DBTestDao(DaoConfig config) {
        super(config);
    }
    
    public DBTestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"com_liushiyu_developer_db_test\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"KEY\" TEXT," + // 1: key
                "\"LOG_TAG\" TEXT," + // 2: logTag
                "\"LOG_STRING\" TEXT);"); // 3: logString
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"com_liushiyu_developer_db_test\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBTest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(2, key);
        }
 
        String logTag = entity.getLogTag();
        if (logTag != null) {
            stmt.bindString(3, logTag);
        }
 
        String logString = entity.getLogString();
        if (logString != null) {
            stmt.bindString(4, logString);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBTest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(2, key);
        }
 
        String logTag = entity.getLogTag();
        if (logTag != null) {
            stmt.bindString(3, logTag);
        }
 
        String logString = entity.getLogString();
        if (logString != null) {
            stmt.bindString(4, logString);
        }
    }

    @Override
    protected final void attachEntity(DBTest entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBTest readEntity(Cursor cursor, int offset) {
        DBTest entity = new DBTest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // logTag
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // logString
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBTest entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLogTag(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLogString(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBTest entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBTest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBTest entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
